### ISSUE TITLE
[问题] 该项目使用的 GMS 版本是什么

### ISSUE THREAD

**Issue by oldkingOK** [znm2500/Undertale-Engine-Ultra#1]
你好，我尝试了以下 GMS 版本，均无法打开或有多处代码语法报错：

- 2024.6.2
- 2023.11.1
- 2023.8.2
- 2022.0.2

想问一下项目所使用的 GMS 版本是什么

**Comment by oldkingOK** [comment]
使用最新版本的 GMS 可以通过编译，但是还是希望在 README 里写上 GMS 版本，谢谢。

**Comment by znm2500** [comment]
啊呀我一般都是用gms最新版，但编译报错可能是我抽风哪里写错代码了，主要我不知道怎么写readme
